### ISSUE TITLE
provide defaults for key, input, S-Box and permutation

### ISSUE THREAD

**Issue by itmm** [itmm/AEStetic#25]
all bits zero,
all bits one,
only one bit set,
one byte ff, rest 00,
random

depends on #3

**Comment by be4** [comment]
The reason for "special" inputs is helping to apply special attack types or visualize a special property:

a) Sample Attack Type: Partial Saturation
Consider 256 chosen plaintexts that have all but 8 of their bits the same, but all differ in those 8 bits.
This means this 1 byte takes all possible values. I expect that then after round 1 all outputs are still different in this byte.
References for partial saturation:
- https://en.wikipedia.org/wiki/Integral_cryptanalysis
- https://www.google.de/url?q=http://th.informatik.uni-mannheim.de/People/Lucks/papers/Att-Twof.ps.gz&sa=U&ved=0ahUKEwiG2e3y4-zJAhXKWSwKHXUJCqwQFggnMAQ&usg=AFQjCNGkbqcr94S2DBDKukgin0FgaiI5dw
- http://math.boisestate.edu/~liljanab/Math509Spring10/AES-security.pdf  (see chapter 8)

b) Sample Property: Diffusion
